### ISSUE TITLE
End of file reached in invalid state for current encoding.

### ISSUE THREAD

**Issue by Neph0** [thirdy/trademacro#2]
Here is the error I get upon pressing ctrl+p while hovering over an item : http://i.imgur.com/ZVP77FA.png

Pressing "Yes" displays me an empty AHK tooltip with the name of the item at the top.

**Comment by ARudiuk** [comment]
Same +1

**Comment by Nevrdid** [comment]
same

**Comment by thirdy** [comment]
Can you guys tell what OS and AHK version you are using?

**Comment by kazuoteramoto** [comment]
I'm also get this, but not always. I'm using Windows 10 (1607) and ahk 1.1.24.00.

**Comment by thirdy** [comment]
Fixed this, please try again

**Comment by ARudiuk** [comment]
I have AHK 1.1.24.01 and win 10. Works for me now! Just had to run as admin
